[package]
name = "random_difference_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.10"
ic-cdk-macros = "0.7"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }